// js/database.js

export const Suits = {
  ORDER: { name: "Ordre", color: "text-blue-400", icon: "🛡️" },
  ARCANE: { name: "Arcane", color: "text-purple-400", icon: "🔮" },
  NOMAD: { name: "Nomade", color: "text-emerald-400", icon: "🏹" },
  DISCORD: { name: "Discorde", color: "text-red-500", icon: "🔥" },
  HEARTH: { name: "Foyer", color: "text-orange-400", icon: "🏠" },
  BEAST: { name: "Bête", color: "text-amber-600", icon: "🐾" },
};

export const AssetConfig = {
  mapsPath: "assets/maps/",
  cardsPath: "assets/cards/",
};

// Génération automatique du dictionnaire complet (198 cartes)
// Chaque image contient une grille de 5 colonnes x 4 lignes
const cardsMeta = [
  // Planche 1 (1 à 20)
  { id: 1, title: "Wrestlers", suit: "ORDER" },
  { id: 2, title: "Battle Honors", suit: "ORDER" },
  { id: 3, title: "Bear Traps", suit: "ORDER" },
  { id: 4, title: "Longbows", suit: "ORDER" },
  { id: 5, title: "Keep", suit: "ORDER" },
  { id: 6, title: "Pressgangs", suit: "ORDER" },
  { id: 7, title: "Garrison", suit: "ORDER" },
  { id: 8, title: "Scouts", suit: "ORDER" },
  { id: 9, title: "Alchemist", suit: "ARCANE" },
  { id: 10, title: "Martial Culture", suit: "ORDER" },
  { id: 11, title: "Errand Boy", suit: "DISCORD" },
  { id: 12, title: "Mercenaries", suit: "DISCORD" },
  { id: 13, title: "Tinker's Fair", suit: "HEARTH" },
  { id: 14, title: "Rain Boots", suit: "NOMAD" },
  { id: 15, title: "A Small Favor", suit: "DISCORD" },
  { id: 16, title: "Second Wind", suit: "DISCORD" },
  { id: 17, title: "Sleight of Hand", suit: "DISCORD" },
  { id: 18, title: "Key to the City", suit: "DISCORD" },
  { id: 19, title: "Scryer", suit: "DISCORD" },
  { id: 20, title: "Disgraced Captain", suit: "DISCORD" },

  // Planche 2 (21 à 40)
  { id: 21, title: "Daysayers", suit: "DISCORD" },
  { id: 22, title: "Book Burning", suit: "DISCORD" },
  { id: 23, title: "Ancient Binding", suit: "NOMAD" },
  { id: 24, title: "Horse Archers", suit: "NOMAD" },
  { id: 25, title: "Warning Signals", suit: "NOMAD" },
  { id: 26, title: "Elders", suit: "NOMAD" },
  { id: 27, title: "The Gathering", suit: "NOMAD" },
  { id: 28, title: "Faithful Friend", suit: "NOMAD" },
  { id: 29, title: "Tents", suit: "NOMAD" },
  { id: 30, title: "Great Herd", suit: "NOMAD" },
  { id: 31, title: "Fire Talkers", suit: "ARCANE" },
  { id: 32, title: "Magician's Code", suit: "ARCANE" },
  { id: 33, title: "Spirit Snare", suit: "ARCANE" },
  { id: 34, title: "Wizard School", suit: "ARCANE" },
  { id: 35, title: "Dazzle", suit: "ARCANE" },
  { id: 36, title: "Acting Troupe", suit: "ARCANE" },
  { id: 37, title: "Taming Charm", suit: "ARCANE" },
  { id: 38, title: "Inquisitor", suit: "ARCANE" },
  { id: 39, title: "Wolves", suit: "BEAST" },
  { id: 40, title: "Animal Playmates", suit: "BEAST" },

  // Planche 3 (41 à 60)
  { id: 41, title: "True Names", suit: "BEAST" },
  { id: 42, title: "The Old Oak", suit: "BEAST" },
  { id: 43, title: "Forest Paths", suit: "BEAST" },
  { id: 44, title: "Long-Lost Heir", suit: "BEAST" },
  { id: 45, title: "Rangers", suit: "BEAST" },
  { id: 46, title: "Roving Terror", suit: "BEAST" },
  { id: 47, title: "Wayside Inn", suit: "HEARTH" },
  { id: 48, title: "Extra Provisions", suit: "HEARTH" },
  { id: 49, title: "Memory of Home", suit: "HEARTH" },
  { id: 50, title: "Welcoming Party", suit: "HEARTH" },
  { id: 51, title: "Traveling Doctor", suit: "HEARTH" },
  { id: 52, title: "Storyteller", suit: "HEARTH" },
  { id: 53, title: "Armed Mob", suit: "HEARTH" },
  { id: 54, title: "Tavern Songs", suit: "HEARTH" },
  { id: 55, title: "Secret Signal", suit: "ARCANE" },
  { id: 56, title: "Augury", suit: "ARCANE" },
  { id: 57, title: "Rusting Ray", suit: "ARCANE" },
  { id: 58, title: "Portal", suit: "ARCANE" },
  { id: 59, title: "Billowing Fog", suit: "ARCANE" },
  { id: 60, title: "Kindred Warriors", suit: "ARCANE" },

  // Planche 4 (61 à 80)
  { id: 61, title: "Terror Spells", suit: "ARCANE" },
  { id: 62, title: "Blood Pact", suit: "ARCANE" },
  { id: 63, title: "Revelation", suit: "ARCANE" },
  { id: 64, title: "Observatory", suit: "ARCANE" },
  { id: 65, title: "Plague Engines", suit: "ARCANE" },
  { id: 66, title: "Gleaming Armor", suit: "ARCANE" },
  { id: 67, title: "Bewitch", suit: "ARCANE" },
  { id: 68, title: "Jinx", suit: "ARCANE" },
  { id: 69, title: "Tutor", suit: "ARCANE" },
  { id: 70, title: "Dream Thief", suit: "ARCANE" },
  { id: 71, title: "Cracking Ground", suit: "ARCANE" },
  { id: 72, title: "Sealing Ward", suit: "ARCANE" },
  { id: 73, title: "Initiation Rite", suit: "ARCANE" },
  { id: 74, title: "Vow of Silence", suit: "ARCANE" },
  { id: 75, title: "Forgotten Vault", suit: "ARCANE" },
  { id: 76, title: "Map Library", suit: "ARCANE" },
  { id: 77, title: "Witch's Bargain", suit: "ARCANE" },
  { id: 78, title: "Master of Disguise", suit: "ARCANE" },
  { id: 79, title: "Charlatan", suit: "DISCORD" },
  { id: 80, title: "Assassin", suit: "DISCORD" },

  // Planche 5 (81 à 100)
  { id: 81, title: "Downtrodden", suit: "DISCORD" },
  { id: 82, title: "Blackmail", suit: "DISCORD" },
  { id: 83, title: "Cracked Sage", suit: "DISCORD" },
  { id: 84, title: "Dissent", suit: "DISCORD" },
  { id: 85, title: "False Prophet", suit: "DISCORD" },
  { id: 86, title: "Vow of Renewal", suit: "DISCORD" },
  { id: 87, title: "Zealots", suit: "DISCORD" },
  { id: 88, title: "Royal Ambitions", suit: "DISCORD" },
  { id: 89, title: "Salt the Earth", suit: "DISCORD" },
  { id: 90, title: "Beast Tamer", suit: "DISCORD" },
  { id: 91, title: "Riots", suit: "DISCORD" },
  { id: 92, title: "Silver Tongue", suit: "DISCORD" },
  { id: 93, title: "Gambling Hall", suit: "DISCORD" },
  { id: 94, title: "Boiling Lake", suit: "DISCORD" },
  { id: 95, title: "Relic Thief", suit: "DISCORD" },
  { id: 96, title: "Enchantress", suit: "DISCORD" },
  { id: 97, title: "Insomnia", suit: "DISCORD" },
  { id: 98, title: "Sneak Attack", suit: "DISCORD" },
  { id: 99, title: "Gossip", suit: "DISCORD" },
  { id: 100, title: "Bandit Chief", suit: "DISCORD" },

  // Planche 6 (101 à 120)
  { id: 101, title: "Chaos Cult", suit: "DISCORD" },
  { id: 102, title: "Slander", suit: "DISCORD" },
  { id: 103, title: "Code of Honor", suit: "ORDER" },
  { id: 104, title: "Outriders", suit: "ORDER" },
  { id: 105, title: "Messenger", suit: "ORDER" },
  { id: 106, title: "Field Promotion", suit: "ORDER" },
  { id: 107, title: "Palanquin", suit: "ORDER" },
  { id: 108, title: "Shield Wall", suit: "ORDER" },
  { id: 109, title: "Military Parade", suit: "ORDER" },
  { id: 110, title: "Tome Guardians", suit: "ORDER" },
  { id: 111, title: "Tyrant", suit: "ORDER" },
  { id: 112, title: "Forced Labor", suit: "ORDER" },
  { id: 113, title: "Secret Police", suit: "ORDER" },
  { id: 114, title: "Specialist", suit: "ORDER" },
  { id: 115, title: "Captains", suit: "ORDER" },
  { id: 116, title: "Siege Engines", suit: "ORDER" },
  { id: 117, title: "Royal Tax", suit: "ORDER" },
  { id: 118, title: "Toll Roads", suit: "ORDER" },
  { id: 119, title: "Curfew", suit: "ORDER" },
  { id: 120, title: "Knights Errant", suit: "ORDER" },

  // Planche 7 (121 à 140)
  { id: 121, title: "Vow of Obedience", suit: "ORDER" },
  { id: 122, title: "Hunting Party", suit: "ORDER" },
  { id: 123, title: "Council Seat", suit: "ORDER" },
  { id: 124, title: "Encirclement", suit: "ORDER" },
  { id: 125, title: "Peace Envoy", suit: "ORDER" },
  { id: 126, title: "Relic Hunter", suit: "ORDER" },
  { id: 127, title: "Homesteaders", suit: "HEARTH" },
  { id: 128, title: "Crop Rotation", suit: "HEARTH" },
  { id: 129, title: "A Round of Ale", suit: "HEARTH" },
  { id: 130, title: "Land Warden", suit: "HEARTH" },
  { id: 131, title: "Charming Friend", suit: "HEARTH" },
  { id: 132, title: "Village Constable", suit: "HEARTH" },
  { id: 133, title: "Family Heirloom", suit: "HEARTH" },
  { id: 134, title: "News from Afar", suit: "HEARTH" },
  { id: 135, title: "Levelers", suit: "HEARTH" },
  { id: 136, title: "Fabled Feast", suit: "HEARTH" },
  { id: 137, title: "The Great Levy", suit: "HEARTH" },
  { id: 138, title: "Hearts and Minds", suit: "HEARTH" },
  { id: 139, title: "Relic Breaker", suit: "HEARTH" },
  { id: 140, title: "Book Binders", suit: "HEARTH" },

  // Planche 8 (141 à 160)
  { id: 141, title: "Ballot Box", suit: "HEARTH" },
  { id: 142, title: "Saddle Makers", suit: "HEARTH" },
  { id: 143, title: "Herald", suit: "HEARTH" },
  { id: 144, title: "Rowdy Pub", suit: "HEARTH" },
  { id: 145, title: "Vow of Peace", suit: "HEARTH" },
  { id: 146, title: "Deed Writer", suit: "HEARTH" },
  { id: 147, title: "Salad Days", suit: "HEARTH" },
  { id: 148, title: "Marriage", suit: "HEARTH" },
  { id: 149, title: "Hospital", suit: "HEARTH" },
  { id: 150, title: "Awaited Return", suit: "HEARTH" },
  { id: 151, title: "Convoys", suit: "NOMAD" },
  { id: 152, title: "Vow of Kinship", suit: "NOMAD" },
  { id: 153, title: "Wild Mounts", suit: "NOMAD" },
  { id: 154, title: "Lancers", suit: "NOMAD" },
  { id: 155, title: "Mountain Giant", suit: "NOMAD" },
  { id: 156, title: "Rival Khan", suit: "NOMAD" },
  { id: 157, title: "Lost Tongue", suit: "NOMAD" },
  { id: 158, title: "Special Envoy", suit: "NOMAD" },
  { id: 159, title: "Resettle", suit: "NOMAD" },
  { id: 160, title: "Oracle", suit: "NOMAD" },

  // Planche 9 (161 à 180)
  { id: 161, title: "Pilgrimage", suit: "NOMAD" },
  { id: 162, title: "Spell Breaker", suit: "NOMAD" },
  { id: 163, title: "Mounted Patrol", suit: "NOMAD" },
  { id: 164, title: "Great Crusade", suit: "NOMAD" },
  { id: 165, title: "Ancient Bloodline", suit: "NOMAD" },
  { id: 166, title: "Ancient Pact", suit: "NOMAD" },
  { id: 167, title: "Storm Caller", suit: "NOMAD" },
  { id: 168, title: "Family Wagon", suit: "NOMAD" },
  { id: 169, title: "Way Station", suit: "NOMAD" },
  { id: 170, title: "Twin Brother", suit: "NOMAD" },
  { id: 171, title: "Hospitality", suit: "NOMAD" },
  { id: 172, title: "A Fast Steed", suit: "NOMAD" },
  { id: 173, title: "Relic Worship", suit: "NOMAD" },
  { id: 174, title: "Sacred Ground", suit: "NOMAD" },
  { id: 175, title: "Nature Worship", suit: "BEAST" },
  { id: 176, title: "Birdsong", suit: "BEAST" },
  { id: 177, title: "Small Friends", suit: "BEAST" },
  { id: 178, title: "Grasping Vines", suit: "BEAST" },
  { id: 179, title: "Threatening Roar", suit: "BEAST" },
  { id: 180, title: "Fae Merchant", suit: "BEAST" },

  // Planche 10 (181 à 198)
  { id: 181, title: "Second Chance", suit: "BEAST" },
  { id: 182, title: "Pied Piper", suit: "BEAST" },
  { id: 183, title: "Mushrooms", suit: "BEAST" },
  { id: 184, title: "Insect Swarm", suit: "BEAST" },
  { id: 185, title: "Vow of Union", suit: "BEAST" },
  { id: 186, title: "Giant Python", suit: "BEAST" },
  { id: 187, title: "War Tortoise", suit: "BEAST" },
  { id: 188, title: "New Growth", suit: "BEAST" },
  { id: 189, title: "Wild Cry", suit: "BEAST" },
  { id: 190, title: "Animal Host", suit: "BEAST" },
  { id: 191, title: "Memory of Nature", suit: "BEAST" },
  { id: 192, title: "Marsh Spirit", suit: "BEAST" },
  { id: 193, title: "Vow of Poverty", suit: "BEAST" },
  { id: 194, title: "Forest Council", suit: "BEAST" },
  { id: 195, title: "Walled Garden", suit: "BEAST" },
  { id: 196, title: "Vow of Beastkin", suit: "BEAST" },
  { id: 197, title: "Bracken", suit: "BEAST" },
  { id: 198, title: "Wild Allies", suit: "BEAST" },
];

export const CardsDatabase = {};

// Calcul mathématique senior de la matrice des Sprites
cardsMeta.forEach((card, idx) => {
  const sheetIndex = Math.floor(idx / 20) + 1; // 20 cartes par image
  const localIdx = idx % 20;
  const col = localIdx % 5; // 5 colonnes
  const row = Math.floor(localIdx / 5); // 4 lignes

  CardsDatabase[`c_${String(card.id).padStart(3, "0")}`] = {
    title: card.title,
    suit: card.suit,
    sprite: {
      sheet: `cards${sheetIndex === 1 ? "" : sheetIndex}.jpg`, // Gère cards.jpg, cards2.jpg...
      col: col,
      row: row,
    },
  };
});

export const PhaseData = {
  wake: {
    num: "Phase I",
    title: "1. Phase de Réveil",
    btn: "Passer aux Actions",
    body: `• <strong>Serment :</strong> Condition de victoire automatique.<br>• <strong>Visions :</strong> Objectifs secrets.`,
  },
  action: {
    num: "Phase II",
    title: "2. Phase d'Actions",
    btn: "Aller au Repos",
    body: `Dépensez vos Provisions (🔹) pour manoeuvrer.`,
  },
  rest: {
    num: "Phase III",
    title: "3. Phase de Repos",
    btn: "Nouveau Tour",
    body: `• <strong>Ravitaillement :</strong> Récupération automatique de Provisions.`,
  },
};
